# Generated by Django 2.0.6 on 2018-07-25 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Position_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.IntegerField(default=0)),
                ('current_prize_money_pos', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Members_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('calculate_team_points', models.IntegerField(default=0)),
                ('credits_left', models.IntegerField(default=0)),
                ('total_cost_players_bought', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('profit_gained_players_sold', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prize_money_minus_bought_sold', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('current_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Current_Position_table')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Info_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='members_table',
            name='personal_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Personal_Info_table'),
        ),
    ]
