# Generated by Django 2.0.6 on 2018-07-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_info_table',
            old_name='display_name',
            new_name='team_name',
        ),
    ]
