# Generated by Django 2.0.6 on 2018-06-07 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_clean_sheets_form_table_goals_assist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Player_table')),
            ],
        ),
        migrations.CreateModel(
            name='Man_of_Match_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Player_table')),
            ],
        ),
        migrations.CreateModel(
            name='Own_Goals_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minus_points', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Player_table')),
            ],
        ),
        migrations.CreateModel(
            name='Red_Card_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minus_points', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Player_table')),
            ],
        ),
        migrations.CreateModel(
            name='Yellow_Car_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minus_points', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Player_table')),
            ],
        ),
        migrations.RenameModel(
            old_name='Clean_Sheets',
            new_name='Clean_Sheets_table',
        ),
        migrations.RenameModel(
            old_name='Goals_Assist',
            new_name='Goals_Assist_table',
        ),
    ]
