# Generated by Django 2.0.6 on 2018-07-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_personal_info_table_has_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_info_table',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='personal_info_table',
            name='email_address',
        ),
    ]
