# Generated by Django 2.0.6 on 2018-07-30 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20180729_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members_table',
            name='personal_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
