# Generated by Django 2.0.6 on 2018-07-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_members_table_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members_table',
            name='total_cost_players_bought',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
