# Generated by Django 2.0.6 on 2018-07-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20180730_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members_table',
            name='prize_money_minus_bought_sold',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='members_table',
            name='profit_gained_players_sold',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
