# Generated by Django 2.0.6 on 2018-07-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20180730_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members_table',
            name='current_position',
        ),
    ]
