# Generated by Django 2.0.6 on 2018-07-30 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0011_members_table_current_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members_table',
            name='current_position',
        ),
        migrations.AddField(
            model_name='current_position_table',
            name='personal_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
