# Generated by Django 2.0.6 on 2018-08-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20180731_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_table',
            name='boolean_team_points',
            field=models.BooleanField(default=True),
        ),
    ]
