# Generated by Django 2.0.6 on 2018-08-10 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_members_table_boolean_team_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members_table',
            name='boolean_team_points',
        ),
        migrations.RemoveField(
            model_name='members_table',
            name='calculate_team_points',
        ),
    ]
