# Generated by Django 2.0.6 on 2018-08-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20180810_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_table',
            name='boolean_team_points',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='members_table',
            name='calculate_team_points',
            field=models.IntegerField(default=0),
        ),
    ]
