# Generated by Django 2.0.6 on 2018-08-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_formations_table_week_no_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='week_table',
            name='current_week',
            field=models.BooleanField(default=False),
        ),
    ]
