# Generated by Django 2.0.6 on 2018-08-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_week_table_current_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtures_table',
            name='competition',
            field=models.CharField(blank=True, choices=[('pl', 'Premier League'), ('cl', 'Champions League')], max_length=50, null=True),
        ),
    ]
