# Generated by Django 2.0.6 on 2018-08-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_auto_20180813_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='week_table',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='week_table',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
