# Generated by Django 2.0.6 on 2018-08-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_auto_20180814_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week_table',
            name='current_week',
        ),
    ]
