# Generated by Django 2.0.6 on 2018-08-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_auto_20180817_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week_table',
            old_name='current_week',
            new_name='is_current_week',
        ),
    ]
