# Generated by Django 2.0.8 on 2018-09-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_auto_20180818_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='week_table',
            old_name='is_current_week',
            new_name='has_this_week_passed',
        ),
    ]
