# Generated by Django 2.0.6 on 2018-07-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='own_goals_table',
            old_name='minus_points',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='red_card_table',
            old_name='minus_points',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='yellow_card_table',
            old_name='minus_points',
            new_name='points',
        ),
    ]
