# Generated by Django 2.0.6 on 2018-07-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20180725_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_table',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
