# Generated by Django 2.0.6 on 2018-07-31 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20180730_2030'),
        ('players', '0006_player_table_player_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('members_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Members_table')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player_table')),
            ],
        ),
        migrations.RemoveField(
            model_name='player_team_table',
            name='members_id',
        ),
        migrations.RemoveField(
            model_name='player_team_table',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='player_team_table',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='team_table',
            name='members_id',
        ),
        migrations.DeleteModel(
            name='Player_Team_table',
        ),
        migrations.DeleteModel(
            name='Team_table',
        ),
    ]
