# Generated by Django 2.0.6 on 2018-07-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_auto_20180731_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_table',
            old_name='player_position',
            new_name='player_position_1',
        ),
        migrations.AddField(
            model_name='player_table',
            name='player_position_2',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player_table',
            name='player_position_3',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
