# Generated by Django 2.0.6 on 2018-07-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20180731_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_table',
            name='player_position_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player_table',
            name='player_position_3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
