# Generated by Django 2.0.6 on 2018-07-31 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20180731_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad_table',
            name='members_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
