# Generated by Django 2.0.6 on 2018-07-31 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_auto_20180731_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squad_table',
            old_name='members_id',
            new_name='user_id',
        ),
    ]
