# Generated by Django 2.0.6 on 2018-08-04 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20180731_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squad_table',
            old_name='player_id',
            new_name='player',
        ),
    ]
