# Generated by Django 2.0.6 on 2018-08-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_auto_20180804_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squad_table',
            old_name='player',
            new_name='player_id',
        ),
    ]
