# Generated by Django 2.0.6 on 2018-08-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_auto_20180804_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad_table',
            name='squad_points',
            field=models.IntegerField(default=0),
        ),
    ]
