# Generated by Django 2.0.6 on 2018-08-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0016_squad_table_squad_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad_table',
            name='squad_points',
        ),
    ]
