# Generated by Django 2.0.6 on 2018-08-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_remove_squad_table_squad_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_table',
            name='is_player_playing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player_table',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
