# Generated by Django 2.0.6 on 2018-08-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_formations_table'),
        ('players', '0019_player_table_week_no_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clean_sheets_table',
            name='week_no_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Week_table'),
        ),
        migrations.AddField(
            model_name='form_table',
            name='week_no_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Week_table'),
        ),
        migrations.AddField(
            model_name='goals_assist_table',
            name='week_no_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Week_table'),
        ),
        migrations.AddField(
            model_name='goals_table',
            name='week_no_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Week_table'),
        ),
        migrations.AddField(
            model_name='man_of_match_table',
            name='week_no_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Week_table'),
        ),
        migrations.AddField(
            model_name='own_goals_table',
            name='week_no_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Week_table'),
        ),
        migrations.AddField(
            model_name='red_card_table',
            name='week_no_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Week_table'),
        ),
        migrations.AddField(
            model_name='yellow_card_table',
            name='week_no_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Week_table'),
        ),
    ]
