# Generated by Django 2.0.6 on 2018-08-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0024_auto_20180813_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad_table',
            name='player',
        ),
        migrations.RemoveField(
            model_name='squad_table',
            name='user',
        ),
        migrations.DeleteModel(
            name='Squad_table',
        ),
    ]
