# Generated by Django 2.0.6 on 2018-08-15 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0026_auto_20180815_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Week_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_no', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='player_table',
            name='week_no_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Player_Week_table'),
        ),
    ]
