# Generated by Django 2.0.6 on 2018-08-16 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0027_auto_20180815_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_week_table',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
