# Generated by Django 2.0.6 on 2018-08-17 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0029_player_week_table_is_new_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_table',
            name='week_no_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Week_table'),
        ),
        migrations.DeleteModel(
            name='Player_Week_table',
        ),
    ]
