# Generated by Django 2.0.6 on 2018-08-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0031_auto_20180820_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clean_sheets_table',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='form_table',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='goals_assist_table',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='goals_table',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='man_of_match_table',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='own_goals_table',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='red_card_table',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='yellow_card_table',
            name='total_points',
        ),
    ]
