# Generated by Django 2.0.6 on 2018-08-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0032_auto_20180820_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals_assist_table',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
