# Generated by Django 2.0.6 on 2018-08-24 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0033_auto_20180824_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals_assist_table',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Player_table'),
        ),
    ]
