# Generated by Django 2.0.6 on 2018-08-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0039_auto_20180824_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_table',
            name='week_no_id',
        ),
    ]
