# Generated by Django 2.0.6 on 2018-08-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0040_remove_player_table_week_no_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_table',
            name='total_points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
