# Generated by Django 2.0.6 on 2018-09-02 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0042_auto_20180902_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalkeeper_table',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
