# Generated by Django 2.0.6 on 2018-09-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0043_auto_20180902_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalkeeper_table',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
