# Generated by Django 2.0.6 on 2018-09-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0044_auto_20180902_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clean_sheets_table',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='form_table',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goals_assist_table',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goals_table',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='man_of_match_table',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='own_goals_table',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='red_card_table',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='yellow_card_table',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
